# Generated by Django 3.2.5 on 2021-07-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_number', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=500)),
                ('is_code', models.BooleanField()),
                ('code', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='return_faces.course')),
            ],
        ),
    ]
