export default {
  course1: {
    screens: [
      'Course1Intro',
      'Course1FaceFinder',
      'Course1HowFindFaces',
      'Course1PinchZoom',
      'Course1Info1',
      'Course1Info2',
      'Course1Brightness1',
      'Course1Brightness1.5',
      'Course1Brightness2',
      'Course1Info3',
      'Course1Info4',
      'Course1Magnify',
      'Course1Info5',
      'Course1HumanVsComputer',
      'Course1HumanVsComputer2',
      'Course1Info6',
      'Course1Info7',
      'Course1Info8',
      'Course1Info9',
      'Course1FaceParts',
      'Course1FaceParts2',
      'Course1Congrats',
      'Course1Review'
    ]
  },
  course2: {
    screens: [
      'Course2Intro',
      'Course2Review1',
      'Course2Review2',
      'Course2Review3',
      'Course2InterpretPictures',
      'Course2OceanNumbers',
      'Course2PixelPatternsText',
      'Course2PixelPatternsInteractive',
      'Course2FilterFeatures1',
      'Course2FilterFeatures2',
      'Course2FilterFeatures3',
      'Course2FilterFeatures4',
      'Course2FilterFeatures5',
      'Course2Contrast1',
      'Course2Contrast2',
      'Course2Contrast3',
      'Course2ContrastMCQ',
      'Course2DraggableFilter',
      'Course2DraggableCompleted',
      'Course2DraggableExplanation',
      'Course2ScanAll1',
      'Course2ScanAll3',
      'Course2ScanAll4',
      'Course2ScanAll5',
      'Course2SearchingAlgorithmFeatures',
      'Course2GettingHangAlgorithms',
      'Course2SearchingAlgorithmMark',
      'Course2Congrats',
      'Course2AlgorithmReview1',
      'Course2AlgorithmReview2',
      'Course2AlgorithmReview3'
    ]
  },
  course3: {
    screens: [
      'Course3Introduction',
      'Course3NearestNeighbor',
      'Course3HouseIntroduction',
      'Course3Distance',
      'Course3Neighborhoods',
      'Course3BlackHouseNeighborhood',
      'Course3NearestNeighborsReveal',
      'Course3CommonTraitQuestion',
      'Course3CommonTraitAnswer',
      'Course3KNNMainIdea',
      'Course3KNNMainIdeaII',
      'Course3KNNMainIdeaIII',
      'Course3KNNMainIdeaIV',
      'Course3KNNMainIdeaV',
      'Course3KNNMainIdeaVI',
      'Course3Congratulations',
      'Course3AlgorithmReview1',
      'Course3AlgorithmReview2',
      'Course3AlgorithmReview3',
      'Course3AlgorithmReview4'
    ]
  },
  section1: {
    screens: ['Course4Intro',
      'Course4IntroRealLifeApplications',
      'Course4InteractiveCaptcha',
      'Course4CaptchaExplanation',
      'Course4NNInfo1',
      'Course4NNInfo2',
      'Course4CompToBrain',
      'Course4Sect1End']
  },
  section2: {
    screens: ['Course4ProcessInfo',
      'Course4NNLayers',
      'Course4LayerInteractive',
      'Course4SelectDNN',
      'Course4SelectDNNCorrect',
      'Course4BPInteractiveIntro',
      'Course4BPInteractiveIntro2',
      'Course4BPInteractive',
      'Course4BPInteractiveReveal',
      'Course4Rematch',
      'Course4BPInteractiveCongrats',
      'Course4BPExplanation1',
      'Course4BPExplanation2',
      'Course4Sect2End']
  },
  section3: {
    buttonWidth: 30,
    screens: ['Course4RealWorldIntro', 'Course4RWInteractive', 'Course4RWInteractiveCorrect', 'Course4RealWorldExplanation', 'Course4Sect3End']
  }
}
