export default {
    course1: {
        screens: [
            'Course1Intro',
            'Course1FaceFinder',
            'Course1HowFindFaces',
            'Course1PinchZoom',
            'Course1Info1',
            'Course1Info2',
            'Course1Brightness1',
            'Course1Brightness1.5',
            'Course1Brightness2',
            'Course1Info3',
            'Course1Info4',
            'Course1Magnify',
            'Course1Info5',
            'Course1HumanVsComputer',
            'Course1HumanVsComputer2',
            'Course1Info6',
            'Course1Info7',
            'Course1Info8',
            'Course1Info9',
            'Course1FaceParts',
            'Course1FaceParts2',
            'Course1Congrats',
            'Course1Review',
        ]
    },
    course2: {
        screens: [
            'Course2Intro',
            'Course2Review1',
            'Course2Review2',
            'Course2Review3',
            'Course2InterpretPictures',
            'Course2OceanNumbers',
            'Course2PixelPatternsText',
            'Course2PixelPatternsInteractive',
            'Course2FilterFeatures1',
            'Course2FilterFeatures2',
            'Course2FilterFeatures3',
            'Course2FilterFeatures4',
            'Course2FilterFeatures5',
            'Course2Contrast1',
            'Course2Contrast2',
            'Course2Contrast3',
            'Course2ContrastMCQ',
            'Course2DraggableFilter',
            'Course2DraggableCompleted',
            'Course2DraggableExplanation',
            'Course2ScanAll1',
            'Course2ScanAll2Wrong',
            'Course2ScanAll2Correct',
            'Course2ScanAll3',
            'Course2ScanAll4',
            'Course2ScanAll5',
            'Course2SearchingAlgorithmFeatures',
            'Course2GettingHangAlgorithms',
            'Course2SearchingAlgorithmMark',
            'Course2Congrats',
            'Course2AlgorithmReview1',
            'Course2AlgorithmReview2',
            'Course2AlgorithmReview3',
            'Course2AppStoreReview',
            'Course2Email',
            'Course2Selfie',
            'Course2FaceDetection',
        ]
    },
    course3: {
        screens: [
            'Course3Introduction',
            'Course3NearestNeighbor',
            'Course3HouseIntroduction',
            'Course3SelectClosestHouse',
            'Course3FollowUp',
            'Course3FollowUpCorrect',
            'Course3FollowUpIncorrect',
            'Course3DistanceRole',
            'Course3Neighborhoods',
            'Course3BlackHouseNeighborhood',
            'Course3GreenHouseNeighborhood',
            'Course3FollowUpIIA',
            'Course3FollowUpIIB',
            'Course3FollowUpIICorrect',
            'Course3FollowUpIIIncorrect',
            'Course3NearestNeighborsReveal',
            'Course3CommonTraitQuestion',
            'Course3CommonTraitAnswer',
            'Course3KNNMainIdea',
            'Course3KNNMainIdeaII',
            'Course3KNNMainIdeaIII',
            'Course3KNNMainIdeaIV',
            'Course3KNNMainIdeaV',
            'Course3KNNMainIdeaVI',
            'Course3Congratulations',
            'Course3AlgorithmReview1',
            'Course3AlgorithmReview2',
            'Course3AlgorithmReview3',
            'Course3AlgorithmReview4',
            'Course3AppStoreReview',
            'Course3Email',
            'Course3Promotion',
        ]
    },
    section1: {
        screens: ['Course4page1_1', 'Course4page1_2', 'Course4page1_3','Course4page1_4', 'Course4page1_5', 'Course4page1_6', 'Course4page1_7','Course4page1_8']
    },
    section2: {
        // screens: ['Test9', 'Test1', 'Test2', 'Test3', 'Test7', 'Test8', 'Test1', 'Test2', 'Test3']
        screens: ['Course4page2_1',
        'Course4page2_2',
        'Course4page2_3',
        'Course4page2_4',
        'Course4page2_4_correct',
        'Course4page2_5',
        'Course4page2_6',
        'Course4page2_7',
        'Course4page2_8',
        'Course4page2_9',
        'Course4page2_10', 
        'Course4page2_11',
        'Course4page2_12',
        'Course4page2_13',
        'Course4page2_14',
        'Course4page2_15',
        'Course4page2_16',
        'Course4page2_17',
        'Course4page2_18']
    },
    section3: {
        buttonWidth: 30,
        screens: ['Course4page3_1','Course4page3_2','Course4page3_2_2','Course4page3_3','Course4page3_4']
    },
}